services:
  - type: web
    name: saanvi-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python python_chatbot_api.py
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
