services:
  - type: web
    name: saanvi-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn python_chatbot_api:app
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
